name: Feature Request
description: Suggest an improvement or new feature
title: "[repo] Brief description of the feature"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement!
        Before submitting, check for [existing issues](../../issues) to avoid duplicates.

  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of the problem or limitation you're facing.
      placeholder: "I'm frustrated when ..."
    validations:
      required: true

  - type: textarea
    id: proposals
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered. Enter `NONE` if not applicable.
    validations:
      required: false

  - type: checkboxes
    id: flags
    attributes:
      label: Additional flags
      options:
        - label: This feature request introduces a breaking change
        - label: This feature request is security-related

  - type: textarea
    id: more-info
    attributes:
      label: Additional context
      description: Any other context, screenshots, or references that support this request.
    validations:
      required: false
