name: Terraform Bug Report
description: Report a bug in a Terraform module
title: "[module-name] Brief description of the bug"
labels: [bug, terraform]
body:
  - type: markdown
    attributes:
      value: |
        Please be cautious with sensitive information or logs while filing this issue.
        Before submitting, check for [existing issues](../../issues) to avoid duplicates.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce-bug
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reproduce the behavior.
      placeholder: |
        1. Use the module with ...
        2. Run `terraform apply` ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: input
    id: module-version
    attributes:
      label: Module version
      description: The version of the module where you encountered this bug.
      placeholder: "1.2.3"
    validations:
      required: true

  - type: input
    id: terraform-version
    attributes:
      label: Terraform / OpenTofu version
      description: Output of `terraform version` or `tofu version`
      placeholder: "v1.x.x"
    validations:
      required: true

  - type: input
    id: provider-versions
    attributes:
      label: Relevant provider versions
      description: Output of `terraform providers` for the providers related to this bug.
      placeholder: "hashicorp/aws v5.x.x, hashicorp/kubernetes v2.x.x"
    validations:
      required: false

  - type: textarea
    id: terraform-config
    attributes:
      label: Terraform configuration
      description: The minimal module configuration that reproduces the issue. Remove any sensitive values.
      placeholder: |
        module "example" {
          source  = "devops-ia/module-name/provider"
          version = "x.x.x"

          # your inputs here
        }
      render: terraform
    validations:
      required: true

  - type: textarea
    id: terraform-output
    attributes:
      label: Error output
      description: The full error or unexpected output from Terraform. This will be formatted as code automatically.
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: security
    attributes:
      label: Security
      description: If this is a vulnerability, report it privately via [GitHub Security Advisory](../../security/advisories/new) instead of opening a public issue.
      options:
        - label: This issue is security-related

  - type: textarea
    id: more-info
    attributes:
      label: Additional context
      description: Any other context, logs, or screenshots that may help diagnose the issue.
    validations:
      required: false
