name: Auto-assign Issue
on:
  workflow_call:
    inputs:
      teams:
        required: true
        type: string
    secrets:
      PAT_GITHUB:
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: "auto-assign issue"
        uses: pozil/auto-assign-issue@v2
        with:
          repo-token: ${{ secrets.PAT_GITHUB }}
          teams: ${{ inputs.teams }}
          removePreviousAssignees: true
