name: EditorConfig Checker

on:
  workflow_call:

permissions:
  contents: read

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Use editorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@3c774f73de01cbec4dc63f87a14f9a5d7cd5b38c # v2.0.0

      - name: Run editorConfig checker
        run: editorconfig-checker
