name: EditorConfig Checker

on:
  workflow_call:

permissions:
  contents: read

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Use editorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@3c774f73de01cbec4dc63f87a14f9a5d7cd5b38c # v2.0.0

      - name: Run editorConfig checker
        run: editorconfig-checker
